# Generated by Django 3.2.6 on 2021-11-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginId',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
